server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com #eureka服务端的实例名称
  client:
    register-with-eureka: true #false表示不向注册中心注册自己
    fetch-registry: false #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址 查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护模式
    enable-self-preservation: false
    #设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    #设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000000
    #集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 60000   